package nicepay

type Response struct {
	TXID           string `json:"tXid"`
	IMID           string `json:"iMid"`
	Currency       string `json:"currency"`
	Amt            string `json:"amt"`
	InstmntMon     string `json:"instmntMon"`
	InstmntType    string `json:"instmntType"`
	ReferenceNo    string `json:"referenceNo"`
	GoodsNm        string `json:"goodsNm"`
	PayMethod      string `json:"payMethod"`
	BillingNm      string `json:"billingNm"`
	ReqDt          string `json:"reqDt"`
	ReqTm          string `json:"reqTm"`
	Status         string `json:"status"`
	ResultCd       string `json:"resultCd"`
	ResultMsg      string `json:"resultMsg"`
	CardNo         string `json:"cardNo"`
	PreauthToken   string `json:"preauthToken"`
	AcquBankCd     string `json:"acquBankCd"`
	IssuBankCd     string `json:"issuBankCd"`
	VacctValidDt   string `json:"vacctValidDt"`
	VacctValidTm   string `json:"vacctValidTm"`
	VacctNo        string `json:"vacctNo"`
	BankCd         string `json:"bankCd"`
	PayNo          string `json:"payNo"`
	MitraCd        string `json:"mitraCd"`
	ReceiptCode    string `json:"receiptCode"`
	CancelAmt      string `json:"cancelAmt"`
	TransDt        string `json:"transDt"`
	TransTm        string `json:"transTm"`
	RecurringToken string `json:"recurringToken"`
	CCTransType    string `json:"ccTransType"`
	PayValidDt     string `json:"payValidDt"`
	PayValidTm     string `json:"payValidTm"`
	MRefNo         string `json:"mRefNo"`
	AcquStatus     string `json:"acquStatus"`
	CardExpYymm    string `json:"cardExpYymm"`
	AcquBankNm     string `json:"acquBankNm"`
	IssuBankNm     string `json:"issuBankNm"`
	DepositDt      string `json:"depositDt"`
	DepositTm      string `json:"depositTm"`
	Description    string `json:"description"`
	AuthNo         string `json:"authNo"`
	Vat            string `json:"vat"`
	Fee            string `json:"fee"`
	NotaxAmt       string `json:"notaxAmt"`
}
